<?php

namespace App\Http\Controllers\Api\UnitTesting;

use App\Http\Controllers\Controller;
use Ixudra\Curl\Facades\Curl;
use App\Models\LogMessage;

class UnitTestingController extends Controller
{
    public function __construct(){
        LogMessage::truncate();
    }

    public function index()
    {
        $sentence = [
            ['cariLokasiDosenGeneral', 'lokasi pak sugi'],
            ['cariLokasiDosenGeneral', 'lokasi pak geri'],
            ['cariLokasiDosenGeneral', 'dimana lokasi pak sugi'],
            ['cariLokasiDosenGeneral', 'dimana lokasi pak geri'],
            ['cariLokasiDosenGeneral', 'pak geri sekarang dimana'],
            ['cariLokasiDosenGeneral', 'sugi posisi'],
            ['cariLokasiDosenGeneral', 'pak sugi dimana'],
            ['cariLokasiDosenGeneral', 'pak sugi sekarang ada dimana'],
            ['cariLokasiDosenGeneral', 'pak sugi sekarang terletak dimana'],
            ['cariJadwalDosenGeneral', 'hari ini pak sugi ngajar apa'],
            ['cariJadwalDosenGeneral', 'jadwal pak sugi hari ini'],
            ['cariJadwalDosenGeneralHari', 'jadwal pak sugi hari rabu'],
            ['cariJadwalDosenGeneralHari', 'hari senin pak geri ngajar apa'],
            ['cariJadwalDosenGeneralHari', 'pak geri mengajar apa hari senin'],
            ['cariJadwalDosenGeneral', 'jadwal pak roe'],
            ['cariJadwalDosenGeneral', 'jadwal mengajar pak sugi'],
            ['cariJadwalDosenGeneralHari', 'jadwal pak agyl hari jumat'],
            ['cariJadwalDosenGeneralHari', 'jadwal pak pangat hari kamis'],
            ['cariJadwalDosenGeneralHari', 'kamis pak sugi ngajar apa'],
            ['cariNomorDosenGeneral', 'carikan nomor telepon pak sugi'],
            ['cariNomorDosenGeneral', 'wa pak sugi'],
            ['cariNomorDosenGeneral', 'telepon pak sugi'],
            ['cariNomorDosenGeneral', 'nomor telepon pak sugi berapa'],
            ['cariNomorDosenGeneral', 'berapa nomor wa pak sugi'],
            ['cariNomorDosenGeneral', 'telepon pak geri berapa'],
            ['cariNomorDosenGeneral', 'pak geri nomor teleponnya apa'],
            ['cariNomorDosenGeneral', 'nomor telepon pak geri'],
            ['cariNomorDosenGeneral', 'tolong nomor telepon pak geri'],
            ['cariNomorDosenGeneral', 'cari nomor pak geri'],
            ['cariJadwalKuliah',        'jadwal kuliah hari ini'],
            ['cariJadwalKuliahNama',    'jadwal kuliah algoritma hari ini'],
            ['cariJadwalKuliahNamaHari', 'jadwal kuliah algoritma hari kamis'],
            ['cariJadwalKuliahNbi',     'jadwal kuliah nbi 1461505115'],
            ['cariJadwalKuliahNamaNbi', 'jadwal kuliah algoritma nbi 1461505115'],
            ['cariJadwalKuliahHariNbi', 'kuliah 1461505115 hari kamis'],
            ['cariJadwalKuliahHari',    'kuliah hari kamis'],
            ['cariJadwalKuliahHariNbi', 'kuliah hari kamis nbi 1461505115'],
            ['cariJadwalKuliah',        'jadwal kuliah sekarang'],
            ['cariJadwalKuliahHariNbi', 'jadwal 1461505115 hari senin'],
            ['cariJadwalKuliah',        'jadwal kuliah hari ini'],
            ['cariJadwalKuliahNama',    'jadwal kuliah pengembangan teknologi web hari ini'],
            ['cariJadwalKuliahNamaHari', 'jadwal kuliah pemrograman game hari senin'],
            ['cariJadwalKuliahNbi',     'jadwal kuliah nbi 1461600076'],
            ['cariJadwalKuliahNamaNbi', 'jadwal kuliah kcbv nbi 1461600076'],
            ['cariJadwalKuliahHariNbi', 'kuliah 1461600076 hari kamis'],
            ['cariJadwalKuliahHari',    'kuliah hari kamis'],
            ['cariJadwalKuliahHariNbi', 'kuliah hari kamis nbi 1461600076'],
            ['cariJadwalKuliah',        'jadwal kuliah sekarang'],
            ['cariJadwalKuliahHariNbi', 'jadwal 1461600076 hari senin'],
            ['cariJadwalKuliah',        'jadwal kuliah hari ini'],
            ['cariJadwalKuliahNama',    'jadwal kuliah algoritma hari ini'],
            ['cariJadwalKuliahNamaHari', 'jadwal kuliah kcbv hari kamis'],
            ['cariJadwalKuliahNbi',     'jadwal kuliah nbi 1461600136'],
            ['cariJadwalKuliahNamaNbi', 'jadwal kuliah komputasi paralel nbi 1461600136'],
            ['cariJadwalKuliahHariNbi', 'kuliah 1461600136 hari kamis'],
            ['cariJadwalKuliahHari',    'kuliah hari selasa'],
            ['cariJadwalKuliahHariNbi', 'kuliah hari rabu nbi 1461600136'],
            ['cariJadwalKuliah',        'jadwal kuliah sekarang'],
            ['cariJadwalKuliahHariNbi', 'jadwal 1461600136 hari jumat'],
            ['cariJadwalKuliah',        'jadwal kuliah hari ini'],
            ['cariJadwalKuliahNama',    'jadwal kuliah imk hari ini'],
            ['cariJadwalKuliahNamaHari', 'jadwal kuliah rekayasa perangkat lunak hari kamis'],
            ['cariJadwalKuliahNbi',     'jadwal kuliah nbi 1461700034'],
            ['cariJadwalKuliahNamaNbi', 'jadwal kuliah teknik kompilasi nbi 1461700034'],
            ['cariJadwalKuliahHariNbi', 'kuliah 1461700034 hari kamis'],
            ['cariJadwalKuliahHari',    'kuliah hari jumat'],
            ['cariJadwalKuliahHariNbi', 'kuliah hari rabu nbi 1461700034'],
            ['cariJadwalKuliah',        'jadwal kuliah sekarang'],
            ['cariJadwalKuliahHariNbi', 'jadwal 1461700034 hari selasa'],
            ['cariJadwalKuliah',        'jadwal kuliah hari ini'],
            ['cariJadwalKuliahNama',    'jadwal kuliah etika teknologi informasi hari ini'],
            ['cariJadwalKuliahNamaHari', 'jadwal kuliah algoritma hari kamis'],
            ['cariJadwalKuliahNbi',     'jadwal kuliah nbi 1461700084'],
            ['cariJadwalKuliahNamaNbi', 'jadwal kuliah aorkom nbi 1461700084'],
            ['cariJadwalKuliahHariNbi', 'kuliah 1461700084 hari kamis'],
            ['cariJadwalKuliahHari',    'kuliah hari senin'],
            ['cariJadwalKuliahHariNbi', 'kuliah hari rabu nbi 1461700084'],
            ['cariJadwalKuliah',        'jadwal kuliah sekarang'],
            ['cariJadwalKuliahHariNbi', 'jadwal 1461700084 hari senin'],
            ['cariJadwalKuliah',        'jadwal kuliah hari ini'],
            ['cariJadwalKuliahNama',    'jadwal kuliah sisdig hari ini'],
            ['cariJadwalKuliahNamaHari', 'jadwal kuliah algoritma hari kamis'],
            ['cariJadwalKuliahNbi',     'jadwal kuliah nbi 1461800033'],
            ['cariJadwalKuliahNamaNbi', 'jadwal kuliah algoritma nbi 1461800033'],
            ['cariJadwalKuliahHariNbi', 'kuliah 1461800033 hari kamis'],
            ['cariJadwalKuliahHari',    'kuliah hari senin'],
            ['cariJadwalKuliahHariNbi', 'kuliah hari selasa nbi 1461800033'],
            ['cariJadwalKuliah',        'jadwal kuliah sekarang'],
            ['cariJadwalKuliahHariNbi', 'jadwal 1461800033 hari rabu'],
            ['cariJadwalKuliah',        'jadwal kuliah hari ini'],
            ['cariJadwalKuliahNama',    'jadwal kuliah algoritma hari ini'],
            ['cariJadwalKuliahNamaHari', 'jadwal kuliah teknik pemrograman lanjut hari kamis'],
            ['cariJadwalKuliahNbi',     'jadwal kuliah nbi 1461800127'],
            ['cariJadwalKuliahNamaNbi', 'jadwal kuliah sistem operasi nbi 1461800127'],
            ['cariJadwalKuliahHariNbi', 'kuliah 1461800127 hari kamis'],
            ['cariJadwalKuliahHari',    'kuliah hari selasa'],
            ['cariJadwalKuliahHariNbi', 'kuliah hari rabu nbi 1461800127'],
            ['cariJadwalKuliah',        'jadwal kuliah sekarang'],
            ['cariJadwalKuliahHariNbi', 'jadwal 1461800127 hari senin'],
            ['cariJadwalKuliah',        'jadwal kuliah hari ini'],
            ['cariJadwalKuliahNama',    'jadwal kuliah ptw hari ini'],
            ['cariJadwalKuliahNamaHari', 'jadwal kuliah so hari kamis'],
            ['cariJadwalKuliahNbi',     'jadwal kuliah nbi 1461809999'],
            ['cariJadwalKuliahNamaNbi', 'jadwal kuliah aorkom nbi 1461809999'],
            ['cariJadwalKuliahHariNbi', 'kuliah 1461809999 hari jumat'],
            ['cariJadwalKuliahHari',    'kuliah hari rabu'],
            ['cariJadwalKuliahHariNbi', 'kuliah hari selasa nbi 1461809999'],
            ['cariJadwalKuliah',        'jadwal kuliah sekarang'],
            ['cariJadwalKuliahHariNbi', 'jadwal 1461809999 hari senin'],
            ['cariJadwalSeminarTA', 'jadwal seminar TA'],
            ['cariJadwalSeminarTANbi', 'seminar TA 1461505276'],
            ['cariJadwalUjianTA', 'jadwal ujian TA'],
            ['cariJadwalUjianTANbi', 'ujian TA 1461505276'],
            ['cariJadwalPendaftaranUjianTA', 'jadwal pendaftaran ujian ta'],
            ['cariJadwalPendaftaranSeminarTA', 'jadwal pendaftaran seminar ta'],
            ['cariProsedurTA', 'prosedur ujian ta'],
            ['cariProsedurSeminarTA', 'prosedur seminar ta'],
            ['cariJadwalSeminarTANbi', 'seminar TA 1461600076'],
            ['cariJadwalUjianTA', 'jadwal ujian TA'],
            ['cariJadwalUjianTANbi', 'ujian TA 1461600076'],
            ['cariPraktikumNama', 'jadwal praktikum daskom'],
            ['cariPraktikumHari','jadwal praktikum hari kamis'],
            ['cariPraktikum', 'jadwal praktikum hari ini'],
            ['cariNilaiPraktikum',      'nilai praktikum 1461505115'],
            ['cariNilaiPraktikumNama',  'nilai praktikum ptw 1461505115'],
            ['cariNilaiPraktikumNama',  'praktikum ptw 1461505115'],
            ['cariNilaiPraktikum',      'praktikum 1461505115'],
            ['cariNilaiPraktikum',    'nilai praktikum 1461600136'],
            ['cariNilaiPraktikumNama', 'nilai praktikum ptw 1461600136'],
            ['cariNilaiPraktikumNama', 'praktikum sisdig 1461600136'],
            ['cariPraktikum',    'praktikum 1461600136'],
            ['cariNilaiPraktikum',    'nilai praktikum 1461700034'],
            ['cariNilaiPraktikumNama', 'nilai praktikum pemrograman dasar 1461700034'],
            ['cariNilaiPraktikumNama', 'praktikum mandatin 1461700034'],
            ['cariNilaiPraktikum',    'praktikum 1461700034'],
            ['cariNilaiPraktikum',    'nilai praktikum 1461700084'],
            ['cariNilaiPraktikumNama', 'nilai praktikum pbo 1461700084'],
            ['cariNilaiPraktikumNama', 'praktikum sistem jarkom 1461700084'],
            ['cariNilaiPraktikum',    'praktikum 1461700084'],
            ['cariNilaiPraktikum',    'nilai praktikum 1461800033'],
            ['cariNilaiPraktikumNama', 'nilai praktikum program dasar 1461800033'],
            ['cariNilaiPraktikumNama', 'praktikum sistem jarkom 1461800033'],
            ['cariPraktikum',    'praktikum 1461800033'],
            ['cariNilaiPraktikum',    'nilai praktikum 1461800127'],
            ['cariNilaiPraktikumNama', 'nilai praktikum program dasar 1461800127'],
            ['cariNilaiPraktikumNama', 'praktikum sistem jarkom 1461800127'],
            ['cariNilaiPraktikum',    'praktikum 1461800127'],
            ['cariJadwalSidangKerjaPraktek', 'jadwal sidang praktek'],
            ['cariJadwalSidangKerjaPraktekNbi', 'jadwal sidang praktek 1461505276'],
            ['cariJadwalPendaftaranKerjaPraktek', 'jadwal pendaftaran sidang kerja praktek'],
            ['cariJadwalSidangKerjaPraktek', 'sidang kerja praktek kapan ?'],
            ['cariJadwalSidangKerjaPraktek', 'carikan jadwal sidang kerja praktek'],
            ['cariJadwalPendaftaranKerjaPraktek', 'pendaftaran sidang kerja praktek'],
            ['cariProsedurKerjaPraktek', 'prosedur kerja praktek'],
            ['cariProsedurKerjaPraktek', 'syarat kerja praktek'],
            ['cariProsedurYudisium', 'prosedur yudisium'],
            ['cariProsedurYudisium', 'syarat yudisium'],
            ['noIntent', 'hai']
        ];

        foreach ($sentence as $key => $value) {
            $response = Curl::to('http://127.0.0.1:3333/api/v1/data/unit-testing')
                ->withData(array('sentence' => $value[1], 'target' => $value[0]))
                ->post();
            $response = json_decode($response);
            $reply = $response->result;
            echo $key." # ".$value[1] . '=>' . $reply;
            echo "<br>";
        }
    }

    public function generate()
    {
        $sentence = [
            'lokasi pak sugi',
            'lokasi pak geri',
            'dimana lokasi pak sugi',
            'dimana lokasi pak geri',
            'pak geri sekarang dimana',
            'sugi posisi',
            'pak sugi dimana',
            'pak sugi sekarang ada dimana',
            'pak sugi sekarang terletak dimana',
            'pak sugi udah dikampus ?',
            'hari ini pak sugi ngajar apa',
            'jadwal pak sugi hari ini',
            'jadwal pak sugi hari rabu',
            'hari senin pak geri ngajar apa',
            'pak geri mengajar apa hari senin',
            'jadwal pak roe',
            'jadwal mengajar pak sugi',
            'jadwal pak agyl hari jumat',
            'jadwal pak pangat hari kamis',
            'kamis pak sugi ngajar apa',
            'carikan nomor telepon pak sugi',
            'wa pak sugi',
            'telepon pak sugi',
            'nomor telepon pak sugi berapa',
            'berapa nomor wa pak sugi',
            'telepon pak geri berapa',
            'pak geri nomor teleponnya apa',
            'nomor telepon pak geri',
            'tolong nomor telepon pak geri',
            'cari nomor pak geri',
            'jadwal kuliah hari ini',
            'jadwal kuliah algoritma hari ini',
            'jadwal kuliah algoritma hari kamis',
            'jadwal kuliah nbi 1461505115',
            'jadwal kuliah algoritma nbi 1461505115',
            'kuliah 1461505115 hari kamis',
            'kuliah hari kamis',
            'kuliah hari kamis nbi 1461505115',
            'jadwal kuliah sekarang',
            'jadwal 1461505115 hari senin',
            'jadwal kuliah hari ini',
            'jadwal kuliah pengembangan teknologi web hari ini',
            'jadwal kuliah pemrograman game',
            'jadwal kuliah nbi 1461600076',
            'jadwal kuliah kcbv nbi 1461600076',
            'kuliah 1461600076 hari kamis',
            'kuliah hari kamis',
            'kuliah hari kamis nbi 1461600076',
            'jadwal kuliah sekarang',
            'jadwal 1461600076 hari senin',
            'jadwal kuliah hari ini',
            'jadwal kuliah algoritma hari ini',
            'jadwal kuliah kcbv hari kamis',
            'jadwal kuliah nbi 1461600136',
            'jadwal kuliah komputasi paralel nbi 1461600136',
            'kuliah 1461600136 hari kamis',
            'kuliah hari selasa',
            'kuliah hari rabu nbi 1461600136',
            'jadwal kuliah sekarang',
            'jadwal 1461600136 hari jumat',
            'jadwal kuliah hari ini',
            'jadwal kuliah imk hari ini',
            'jadwal kuliah rekayasa perangkat lunak hari kamis',
            'jadwal kuliah nbi 1461700034',
            'jadwal kuliah teknik kompilasi nbi 1461700034',
            'kuliah 1461700034 hari kamis',
            'kuliah hari jumat',
            'kuliah hari rabu nbi 1461700034',
            'jadwal kuliah sekarang',
            'jadwal 1461700034 hari selasa',
            'jadwal kuliah hari ini',
            'jadwal kuliah etika teknologi informasi hari ini',
            'jadwal kuliah algoritma hari kamis',
            'jadwal kuliah nbi 1461700084',
            'jadwal kuliah aorkom nbi 1461700084',
            'kuliah 1461700084 hari kamis',
            'kuliah hari senin',
            'kuliah hari rabu nbi 1461700084',
            'jadwal kuliah sekarang',
            'jadwal 1461700084 hari senin',
            'jadwal kuliah hari ini',
            'jadwal kuliah sisdig hari ini',
            'jadwal kuliah algoritma hari kamis',
            'jadwal kuliah nbi 1461800033',
            'jadwal kuliah algoritma nbi 1461800033',
            'kuliah 1461800033 hari kamis',
            'kuliah hari senin',
            'kuliah hari selasa nbi 1461800033',
            'jadwal kuliah sekarang',
            'jadwal 1461800033 hari rabu',
            'jadwal kuliah hari ini',
            'jadwal kuliah algoritma hari ini',
            'jadwal kuliah teknik pemrograman lanjut hari kamis',
            'jadwal kuliah nbi 1461800127',
            'jadwal kuliah sistem operasi nbi 1461800127',
            'kuliah 1461800127 hari kamis',
            'kuliah hari selasa',
            'kuliah hari rabu nbi 1461800127',
            'jadwal kuliah sekarang',
            'jadwal 1461800127 hari senin',
            'jadwal kuliah hari ini',
            'jadwal kuliah ptw hari ini',
            'jadwal kuliah so hari kamis',
            'jadwal kuliah nbi 1461809999',
            'jadwal kuliah aorkom nbi 1461809999',
            'kuliah 1461809999 hari jumat',
            'kuliah hari rabu',
            'kuliah hari selasa nbi 1461809999',
            'jadwal kuliah sekarang',
            'jadwal 1461809999 hari senin',
            'jadwal seminar TA',
            'seminar TA 1461505276',
            'jadwal ujian TA',
            'ujian TA 1461505276',
            'jadwal pendaftaran ujian ta',
            'jadwal pendaftaran seminar ta',
            'prosedur ujian ta',
            'prosedur seminar ta',
            'seminar TA 1461600076',
            'jadwal ujian TA',
            'ujian TA 1461600076',
            'jadwal praktikum daskom',
            'jadwal praktikum hari kamis',
            'jadwal praktikum hari ini',
            'nilai praktikum 1461505115',
            'nilai praktikum ptw 1461505115',
            'praktikum ptw 1461505115',
            'praktikum 1461505115',
            'nilai praktikum 1461600136',
            'nilai praktikum ptw 1461600136',
            'praktikum sisdig 1461600136',
            'praktikum 1461600136',
            'nilai praktikum 1461700034',
            'nilai praktikum pemrograman dasar 1461700034',
            'praktikum mandatin 1461700034',
            'praktikum 1461700034',
            'nilai praktikum 1461700084',
            'nilai praktikum pbo 1461700084',
            'praktikum sistem jarkom 1461700084',
            'praktikum 1461700084',
            'nilai praktikum 1461800033',
            'nilai praktikum program dasar 1461800033',
            'praktikum sistem jarkom 1461800033',
            'praktikum 1461800033',
            'nilai praktikum 1461800127',
            'nilai praktikum program dasar 1461800127',
            'praktikum sistem jarkom 1461800127',
            'praktikum 1461800127',
            'jadwal sidang praktek',
            'jadwal sidang praktek 1461505276',
            'jadwal pendaftaran sidang kerja praktek',
            'sidang kerja praktek kapan ?',
            'carikan jadwal sidang kerja praktek',
            'pendaftaran sidang kerja praktek',
            'prosedur kerja praktek',
            'syarat kerja praktek',
            'prosedur yudisium',
            'syarat yudisium'
        ];

        foreach ($sentence as $key => $value) {
            echo $key;
            echo $value;
            $response = Curl::to('http://127.0.0.1:3333/api/v1/data/extraction')
                ->withData(array('sentence' => $value))
                ->post();
            $response = json_decode($response);
            $reply = $response->result;
            echo $value . '=>' . $reply;
            echo "\r\n";
        }
    }
}
